# 网站基本信息
title: "张三的个人博客"
description: "一个分享技术、设计和生活的个人博客"
baseurl: ""
url: "https://yourdomain.com"
language: "zh-CN"

# 作者信息
author:
  name: "张三"
  bio: "一名全栈开发者，热爱编程和设计"
  location: "中国北京"
  email: "your.email@example.com"

# 社交媒体
twitter_username: yourusername
github_username: yourusername
linkedin_username: yourusername

# 博客设置
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# 评论系统设置
comments:
  provider: "disqus" # 可选: disqus, gitalk, valine等
  disqus:
    shortname: "your-disqus-shortname"
  gitalk:
    clientID: "your-client-id"
    clientSecret: "your-client-secret"
    repo: "your-username.github.io"
    owner: "your-username"
    admin: ["your-username"]

# 搜索功能
search: true

# 分析工具
google_analytics: "G-MEASUREMENT_ID"
baidu_analytics: "your-baidu-analytics-id"

# Jekyll设置
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

# 分类和标签设置
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
