title: 我的博客
email: Cao_mouiller@163.com
description: 分享技术见解和项目经验的个人博客
baseurl: "" # 如果是自定义域名或 username.github.io 则留空
url: "" 

# 社交媒体
github_username: https://github.com/Orlando-Lin

# 主题设置
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# 构建设置
permalink: /:categories/:title/
sass:
  sass_dir: _sass
  style: compressed

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md 