source "https://rubygems.org"
gem "jekyll", "~> 4.3.2"
gem "minima", "~> 2.5"
gem "jekyll-feed", "~> 0.17.0"
gem "jekyll-seo-tag", "~> 2.8.0"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "webrick", "~> 1.8"
gem "jekyll-archives"
